POST http://localhost:3000/inicio/user
Content-Type: application/json 

{
  "nombre": "hhvj",
  "nickname": "nick",
  "contrasena": "contra",
  "email":"email"
}
###
//DELETE   http://localhost:3000/inicio/5e2fa593e438e8347cb7f7bf
GET http://localhost:3000/inicio/user
